"""empty message

Revision ID: 04bf623791f9
Revises: b8b5680f54be
Create Date: 2025-11-26 15:05:00.328672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bf623791f9'
down_revision: Union[str, Sequence[str], None] = 'b8b5680f54be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sent_comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('comment_id', sa.String(length=255), nullable=False),
    sa.Column('ticket_id', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sent_comments'))
    )
    op.create_index(op.f('ix_sent_comments_comment_id'), 'sent_comments', ['comment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sent_comments_comment_id'), table_name='sent_comments')
    op.drop_table('sent_comments')
    # ### end Alembic commands ###
