"""empty message

Revision ID: 2a690259dfb3
Revises: 4738ae418cce
Create Date: 2025-11-23 14:44:08.381652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a690259dfb3'
down_revision: Union[str, Sequence[str], None] = '4738ae418cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_settings', sa.Column('email_login', sa.String(length=255), nullable=False))
    op.add_column('email_settings', sa.Column('email_password', sa.String(length=255), nullable=False))
    op.add_column('email_settings', sa.Column('smtp_host', sa.String(length=255), nullable=False))
    op.add_column('email_settings', sa.Column('imap_host', sa.String(length=255), nullable=False))
    op.add_column('email_settings', sa.Column('imap_port', sa.Integer(), nullable=False))
    op.alter_column('email_settings', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('email_settings', 'smtp_password')
    op.drop_column('email_settings', 'smtp_url')
    op.drop_column('email_settings', 'user_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email_settings', sa.Column('user_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('email_settings', sa.Column('smtp_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('email_settings', sa.Column('smtp_password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.alter_column('email_settings', 'description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('email_settings', 'imap_port')
    op.drop_column('email_settings', 'imap_host')
    op.drop_column('email_settings', 'smtp_host')
    op.drop_column('email_settings', 'email_password')
    op.drop_column('email_settings', 'email_login')
    # ### end Alembic commands ###
