"""empty message

Revision ID: b8b5680f54be
Revises: 375b0ac5cb6d
Create Date: 2025-11-23 14:53:05.097355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8b5680f54be'
down_revision: Union[str, Sequence[str], None] = '375b0ac5cb6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('received_emails',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email_settings_id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('is_processed_by_api', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['email_settings_id'], ['email_settings.id'], name=op.f('fk_received_emails_email_settings_id_email_settings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_received_emails'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('received_emails')
    # ### end Alembic commands ###
