name: Python Code Quality
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - name: Linting
        run: uv run ruff check .

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup
      - name: Formatting
        run: uv run ruff format --check .

  type_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Type Consistency
        run: uv run pyright .
